### ISSUE TITLE
steamroller used by log4js-node?

### ISSUE THREAD

**Issue by gee4vee** [log4js-node/streamroller#136]
Does log4js use `steamroller` for log file rotation? We are getting a maximum call stack size exceeded error with `steamroller` calls but we don't explicitly use this package. We do use `multiFile` appender with a few backups.

```
"RangeError: Maximum call stack size exceeded
    at Object.mkdirSync (node:fs:1316:19)
    at mkdir (/Users/gvalenc/git/DevX/solutions-sdk-ts/node_modules/streamroller/lib/RollingFileWriteStream.js:246:19)
    at mkdir (/Users/gvalenc/git/DevX/solutions-sdk-ts/node_modules/streamroller/lib/RollingFileWriteStream.js:252:11)
    at mkdir (/Users/gvalenc/git/DevX/solutions-sdk-ts/node_modules/streamroller/lib/RollingFileWriteStream.js:253:18)
    at mkdir (/Users/gvalenc/git/DevX/solutions-sdk-ts/node_modules/streamroller/lib/RollingFileWriteStream.js:253:18)
    at mkdir (/Users/gvalenc/git/DevX/solutions-sdk-ts/node_modules/streamroller/lib/RollingFileWriteStream.js:253:18)
    at mkdir (/Users/gvalenc/git/DevX/solutions-sdk-ts/node_modules/streamroller/lib/RollingFileWriteStream.js:253:18)
    at mkdir (/Users/gvalenc/git/DevX/solutions-sdk-ts/node_modules/streamroller/lib/RollingFileWriteStream.js:253:18)
    at mkdir (/Users/gvalenc/git/DevX/solutions-sdk-ts/node_modules/streamroller/lib/RollingFileWriteStream.js:253:18)
    at mkdir (/Users/gvalenc/git/DevX/solutions-sdk-ts/node_modules/streamroller/lib/RollingFileWriteStream.js:253:18)"
```

**Comment by peteriman** [comment]
`log4js@6.5.0` ([changelog](https://github.com/log4js-node/log4js-node/blob/v6.5.0/CHANGELOG.md)) and `streamroller@3.1.0` ([changelog](https://github.com/log4js-node/streamroller/blob/v3.1.0/CHANGELOG.md)) now supports tilde expansions
